spring.application.name=StworzGrafik

spring.profiles.default=local

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

logging.level.org.flywaydb=DEBUG

spring.docker.compose.enabled=false

spring.jackson.time-format=HH:mm

# =========================
# KAFKA
# =========================
app.kafka.demo.partitions=${KAFKA_DEMO_PARTITIONS:1}
app.kafka.demo.replication-factor=${KAFKA_DEMO_REPLICATION_FACTOR:1}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=online.stworzgrafik.StworzGrafik.demo.DTO

# =========================
# DEMO
# =========================
app.demo.ttl-minutes=${DEMO_TTL_MINUTES:60}
app.demo.expiration-check-ms=${DEMO_EXPIRATION_CHECK_MS:60000}

# =========================
# JWT
# =========================
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION:86400000}


# =========================
# CLOUDFLARE
# =========================
cloudflare.r2.endpoint=${CLOUDFLARE_R2_ENDPOINT:https://placeholder.r2.cloudflarestorage.com}
cloudflare.r2.access-key=${CLOUDFLARE_R2_ACCESS_KEY:placeholder}
cloudflare.r2.secret-key=${CLOUDFLARE_R2_SECRET_KEY:placeholder}
cloudflare.r2.bucket=${CLOUDFLARE_R2_BUCKET:stworzgrafik-exports}
cloudflare.r2.presigned-url-expiry-minutes=${CLOUDFLARE_R2_EXPIRY_MINUTES:15}


