package online.stworzgrafik.StworzGrafik.schedule.message;

public enum ScheduleMessageCode {
    DEMAND_DRAFT_NOT_COVERED,
    TOO_MANY_EMPLOYEE_PROPOSALS,
    EMPLOYEE_DOUBLE_PROPOSAL,
    NO_EMPLOYEE_TO_COVER_WAREHOUSEMAN,
    EMPLOYEE_MONTHLY_SUM_OF_HOURS_EXCEEDED,
    EMPLOYEE_MONTHLY_MAX_WORKING_DAYS_EXCEEDED,
}
